In [8]:
import numpy as np

In [9]:
minha_lista = [1,2,3]

In [10]:
minha_lista

[1, 2, 3]

In [11]:
np.array(minha_lista)

array([1, 2, 3])

In [12]:
minha_matriz = [(1,2,3),(4,5,6),(7,8,9)]

In [13]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
arr = np.zeros(3)

In [18]:
arr

array([0., 0., 0.])

In [19]:
arr = np.zeros((5,5))

In [20]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.linspace(0,10,2)

array([ 0., 10.])

In [24]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [25]:
np.random.rand(5)

array([0.75528854, 0.42414842, 0.28834328, 0.37577373, 0.93899783])

In [26]:
np.random.rand(5,4)

array([[4.82244450e-01, 1.07967311e-01, 1.59552501e-01, 7.64814046e-01],
       [1.65204226e-01, 5.23589405e-01, 6.22892966e-01, 7.04536524e-01],
       [8.75908239e-01, 7.84405201e-01, 1.03780484e-01, 2.28519929e-01],
       [8.81277950e-01, 2.67738534e-01, 3.12692207e-05, 9.03273491e-01],
       [6.92205831e-01, 4.31556034e-01, 4.01673684e-01, 7.80695059e-01]])

In [28]:
np.random.randn(5)

array([ 0.77502994, -0.95108831,  0.42891683,  0.88789932, -0.48123597])

In [29]:
np.random.randint(0,100,10)

array([46, 68,  7, 80, 91,  2, 33, 91, 40, 32])

In [31]:
np.random.rand(5) * 100

array([ 6.09077848, 10.06703456, 72.66672486, 61.68447822, 33.47185402])

In [32]:
np.round(np.random.rand(5)*100,0)

array([16., 42., 75., 19., 41.])

In [33]:
arr = np.random.rand(25)

In [34]:
arr

array([0.5052731 , 0.77519296, 0.25798956, 0.20251233, 0.97770032,
       0.33103044, 0.3456959 , 0.11907121, 0.86182306, 0.4839601 ,
       0.82749062, 0.12457641, 0.7541738 , 0.76166398, 0.79462909,
       0.31683737, 0.31738176, 0.98702205, 0.18400625, 0.74575869,
       0.28135811, 0.40937965, 0.61054517, 0.34772282, 0.8047711 ])

In [35]:
arr.reshape((5,5))

array([[0.5052731 , 0.77519296, 0.25798956, 0.20251233, 0.97770032],
       [0.33103044, 0.3456959 , 0.11907121, 0.86182306, 0.4839601 ],
       [0.82749062, 0.12457641, 0.7541738 , 0.76166398, 0.79462909],
       [0.31683737, 0.31738176, 0.98702205, 0.18400625, 0.74575869],
       [0.28135811, 0.40937965, 0.61054517, 0.34772282, 0.8047711 ]])

In [37]:
arr= arr.reshape((5,5))

In [38]:
arr

array([[0.5052731 , 0.77519296, 0.25798956, 0.20251233, 0.97770032],
       [0.33103044, 0.3456959 , 0.11907121, 0.86182306, 0.4839601 ],
       [0.82749062, 0.12457641, 0.7541738 , 0.76166398, 0.79462909],
       [0.31683737, 0.31738176, 0.98702205, 0.18400625, 0.74575869],
       [0.28135811, 0.40937965, 0.61054517, 0.34772282, 0.8047711 ]])

In [39]:
arr.shape

(5, 5)

In [40]:
arr.max()

0.9870220496879731

In [41]:
arr.min()

0.11907121420909528

In [43]:
arr.argmax()

17

In [44]:
arr.argmin()

7